### ISSUE TITLE
ACME server that is running in docker container generates error with this image when generating certs

### ISSUE THREAD

**Issue by flikites** [RunOnFlux/flux-mini-fdm#4]
So I have this really weird case happening with the generated docker image:  ```alihmahdavi/flux-mini-fdm:latest```

I'm testing two different ACME servers, same source code, only difference is one is running in a docker container and the other runs as a systemd service. 

https://acme.slyfi.com/directory (Docker Container) - This one does not generate certificates using the generated docker image. 

https://acme.htools.work/directory (Systemd Service) - This one does generate certificates using the generated docker image.

The error that the docker based ACME server throws is:

```cryptography.x509.base.InvalidVersion: 2 is not a valid CSR version```

I've tested the acme.slyfi.com server using my caddy proxy docker image, and it generated the certs just fine.

https://github.com/FliKites/caddy-proxy `wirewrex/caddy-hns:test`

This leads me to believe that their *may* be an issue with the certbot client that is packaged into this repo. 

You can reproduce the error by deploying an instance of the flux-mini-fdm with the docker image ```alihmahdavi/flux-mini-fdm:latest``` using each of the acme servers and then comparing the results from the log output.

**Comment by alihm** [comment]
strange, certbot client should be the latest from debian repo. Will look into it.

**Comment by flikites** [comment]
Here is what the logs look like from the acme server end for each client: 
Certbot from this repo
```
18.141.24.227 - - [01/Jan/2023:05:05:36 +0000] 'GET /directory HTTP/1.1' 200 193 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 6992µs
18.141.24.227 - - [01/Jan/2023:05:05:37 +0000] 'HEAD /newNonce HTTP/1.1' 200 0 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 6964µs
18.141.24.227 - - [01/Jan/2023:05:05:37 +0000] 'POST /newAccount HTTP/1.1' 201 155 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 23312µs
18.141.24.227 - - [01/Jan/2023:05:05:38 +0000] 'POST /newOrder HTTP/1.1' 201 342 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 28415µs
18.141.24.227 - - [01/Jan/2023:05:05:39 +0000] 'POST /authorization/urn:uuid:64188f31-0209-4ec8-a90c-0257b852cf86 HTTP/1.1' 200 356 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 19193µs
18.141.24.227 - - [01/Jan/2023:05:05:40 +0000] 'POST /challenge/urn:uuid:3a62f946-3331-43ef-8792-c81990b524d0 HTTP/1.1' 200 233 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 687422µs
18.141.24.227 - - [01/Jan/2023:05:05:44 +0000] 'POST /authorization/urn:uuid:64188f31-0209-4ec8-a90c-0257b852cf86 HTTP/1.1' 200 401 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 19636µs
[2023-01-01 05:05:44,973] ERROR in flask_handlers: serverInternal (500): 2 is not a valid CSR version
[2023-01-01 05:05:44,974] ERROR in flask_handlers: Traceback (most recent call last):
  File "/opt/serles_venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/serles_venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/serles_venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/serles_venv/lib/python3.8/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/opt/serles_venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/serles/views.py", line 241, in post
    certificate = check_csr_and_return_cert(csr, order)
  File "/app/serles/challenge.py", line 203, in check_csr_and_return_cert
    csr = x509.load_der_x509_csr(csr_der, x509_backend())
  File "/opt/serles_venv/lib/python3.8/site-packages/cryptography/x509/base.py", line 542, in load_der_x509_csr
    return rust_x509.load_der_x509_csr(data)
cryptography.x509.base.InvalidVersion: 2 is not a valid CSR version

18.141.24.227 - - [01/Jan/2023:05:05:44 +0000] 'POST /order/urn:uuid:0b2ef114-74cb-4c11-b02e-a123bf078047/finalize HTTP/1.1' 500 93 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 19770µs
/opt/serles_venv/lib/python3.8/site-packages/flask/app.py:2218: UserWarning: Current server name '18.210.168.204' doesn't match configured server name 'acme.slyfi.com'
  return self.url_map.bind_to_environ(
```

Caddy from the caddy-proxy repo:
```
146.190.112.16 - - [01/Jan/2023:06:22:12 +0000] 'GET /directory HTTP/1.1' 200 193 '-' 'CertMagic Caddy/1.0.3 xenolf-acme/2.5.0 (release; linux; amd64)' in 16396µs
146.190.112.16 - - [01/Jan/2023:06:22:12 +0000] 'HEAD /newNonce HTTP/1.1' 200 0 '-' 'CertMagic Caddy/1.0.3 xenolf-acme/2.5.0 (release; linux; amd64)' in 6226µs
146.190.112.16 - - [01/Jan/2023:06:22:13 +0000] 'POST /newAccount HTTP/1.1' 201 157 '-' 'CertMagic Caddy/1.0.3 xenolf-acme/2.5.0 (release; linux; amd64)' in 24028µs
146.190.112.16 - - [01/Jan/2023:06:22:13 +0000] 'POST /newOrder HTTP/1.1' 201 329 '-' 'CertMagic Caddy/1.0.3 xenolf-acme/2.5.0 (release; linux; amd64)' in 29377µs
146.190.112.16 - - [01/Jan/2023:06:22:13 +0000] 'POST /authorization/urn:uuid:6f1d6482-ab1b-4415-8f81-7c0ad785bc54 HTTP/1.1' 200 343 '-' 'CertMagic Caddy/1.0.3 xenolf-acme/2.5.0 (release; linux; amd64)' in 20624µs
146.190.112.16 - - [01/Jan/2023:06:22:14 +0000] 'POST /challenge/urn:uuid:e50f9a39-df6d-45d5-aba4-47650011e54e HTTP/1.1' 200 233 '-' 'CertMagic Caddy/1.0.3 xenolf-acme/2.5.0 (release; linux; amd64)' in 457522µs
New request: got.dssl ['got.dssl'] wirewrex@protonmail.com
Generating ephemeral CA...
Building certificate...
Signing certificate...
Bundling certificates...
TLSA: _443._tcp.got.dssl. TLSA 3 1 1 a6a14168d8ebaa76eb7f48443b122c2a6ed973e1e369dd0d0b2ad160860d9f9f
Done!
146.190.112.16 - - [01/Jan/2023:06:22:15 +0000] 'POST /order/urn:uuid:5304315e-9401-4b97-8fd3-45a6ed05118d/finalize HTTP/1.1' 200 419 '-' 'CertMagic Caddy/1.0.3 xenolf-acme/2.5.0 (release; linux; amd64)' in 1385823µs
146.190.112.16 - - [01/Jan/2023:06:22:16 +0000] 'POST /cert/urn:uuid:7a89499d-adb6-441e-99b0-3aa6ca1f8054 HTTP/1.1' 200 1938 '-' 'CertMagic Caddy/1.0.3 xenolf-acme/2.5.0 (release; linux; amd64)' in 23779µs
```

Not sure why the certbot client ends up using the IP, seems to be breaking the ACME server because the URL needs to match.

```
18.141.24.227 - - [01/Jan/2023:05:05:44 +0000] 'POST /order/urn:uuid:0b2ef114-74cb-4c11-b02e-a123bf078047/finalize HTTP/1.1' 500 93 '-' 'CertbotACMEClient/0.31.0 (certbot; Debian GNU/Linux 10 (buster)) Authenticator/standalone Installer/None (certonly; flags: n) Py/3.7.3' in 19770µs
/opt/serles_venv/lib/python3.8/site-packages/flask/app.py:2218: UserWarning: Current server name '18.210.168.204' doesn't match configured server name 'acme.slyfi.com'
  return self.url_map.bind_to_environ(
```

Gonna try something on my end, maybe reverse proxing the gunicorn server will fix this.
